name: MeetX CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-client:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: client

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Client Dependencies
        run: npm install

      - name: Build Client
        run: npm run build

  build-server:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: server

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Server Dependencies
        run: npm install